FROM registry-internal.cn-hangzhou.aliyuncs.com/rubberboy/php:5.3
MAINTAINER rubberBoy <gaosheng08@gmail.com>

ENV MYSQL_VERSION 5.6.34

COPY software/mysql-$MYSQL_VERSION.tar.gz /opt/mysql-$MYSQL_VERSION.tar.gz
COPY software/init_mysql.sh /opt/init_mysql.sh

RUN yum install cmake bison ncurses -y

#mysql
RUN cd /opt \
	&& tar -xzvf mysql-$MYSQL_VERSION.tar.gz \
	&& cd mysql-$MYSQL_VERSION \
	&& cmake . \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf mysql-$MYSQL_VERSION* \
	&& groupadd mysql \
	&& useradd -g mysql mysql \
	&& /usr/local/mysql/scripts/mysql_install_db \
		--user=mysql \
		--basedir=/usr/local/mysql \
		--datadir=/usr/local/mysql/data \
	&& mv /usr/local/mysql/my.cnf /etc \
	&& chmod u+x /opt/init_mysql.sh \
	&& /opt/init_mysql.sh
