FROM registry-internal.cn-hangzhou.aliyuncs.com/rubberboy/php:5.3
MAINTAINER rubberBoy <gaosheng08@gmail.com>

ENV MEMCACHED 1.4.33
ENV MEMCACHE 2.2.7

COPY software/memcached-$MEMCACHED.tar.gz /opt/memcached-$MEMCACHED.tar.gz
COPY software/memcache-.tgz /opt/memcache-$MEMCACHE.tgz

RUN yum install libevent libevent-devel -y

# memcached 服务端
RUN cd /opt \
	&& tar -xzvf memcached-$MEMCACHED.tar.gz \
	&& cd memcached-MEMCACHED \
	&& ./configure --prefix=/usr/local/memcached \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf memcached-MEMCACHED*

# php memcache 扩展
RUN cd /opt \
	&& tar -xzvf memcache-$MEMCACHE.tgz \
	&& cd memcache-$MEMCACHE \
	&& /usr/local/php/bin/phpize \
	&& ./configure --with-php-config=/usr/local/php/bin/php-config \
	&& make && make install \
	&& cd ../ \
	&& rm -rf memcache-$MEMCACHE* \
	&& echo "[memcache]" >> /usr/local/php/lib/php.ini \
	&& echo "extension=/usr/local/php/lib/php/extensions/no-debug-zts-20090626/memcache.so" >> /usr/local/php/lib/php.ini

