FROM centos:6.6
MAINTAINER rubberBoy <gaosheng08@gmail.com>

### -------------------------------------- sshd start --------------------------------------
RUN yum install -y yum-plugin-ovl gcc gcc-c++ glibc glibc-devel glib2 glib2-devel openssl-devel curl tar wget telnet \
	&& yum install -y passwd openssl openssh-server \
	&& yum clean all 

RUN ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key \
        && ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key \
        && ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N "" \
        && sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config	\
        && sed -i 's/^root.*/root:$6$flMoy3hB$v3a.GohI8oipbH2DLd6TYorIUkvYPb2qJAc6yNsId7CVQPCpKjIG9EilgZxHREfYHAZhCMlqkUnfgfYpSp6yP1:17116:0:99999:7:::/g' /etc/shadow
### -------------------------------------- sshd end --------------------------------------

### -------------------------------------- apache start --------------------------------------
ENV APR_VERSION 1.5.2
ENV APR_UTIL_VERSION 1.5.4
ENV PCRE_VERSION 8.39
ENV APACHE_VERSION 2.4.23

COPY apache/software/httpd-$APACHE_VERSION.tar.gz /opt/httpd-$APACHE_VERSION.tar.gz
COPY apache/software/apr-util-$APR_UTIL_VERSION.tar.gz /opt/apr-util-$APR_UTIL_VERSION.tar.gz
COPY apache/software/apr-$APR_VERSION.tar.gz /opt/apr-$APR_VERSION.tar.gz
COPY apache/software/pcre-$PCRE_VERSION.tar.gz /opt/pcre-$PCRE_VERSION.tar.gz

#环境准备
RUN yum install -y autoconf libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libpng libpng-devel libxml2 libxml2-devel zlib zlib-devel bzip2 bzip2-devel ncurses gdbm-devel db4-devel libXpm-devel libX11-devel gd-devel gmp-devel readline-devel libxslt-devel expat-devel xmlrpc-c xmlrpc-c-devel libtool libtool-ltdl libtool-ltdl-devel mysql-devel

#apr 
RUN cd /opt/ \
#	&& wget http://apache.mirrors.pair.com/apr/apr-$APR_VERSION.tar.gz \
	&& tar -xzvf apr-$APR_VERSION.tar.gz \
	&& cd apr-$APR_VERSION \
	&& sed -i "s/RM='\$RM'/RM='\$RM -f'/g" configure \
	&& ./configure --prefix=/usr/local/apr \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf apr-$APR_VERSION*

#apr-util
RUN cd /opt/ \
#	&& wget http://apache.mirrors.pair.com/apr/apr-util-$APR_UTIL_VERSION.tar.gz \
	&& tar -xzvf apr-util-$APR_UTIL_VERSION.tar.gz \
	&& cd apr-util-$APR_UTIL_VERSION \
	&& ./configure --prefix=/usr/local/apr-util -with-apr=/usr/local/apr/bin/apr-1-config \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf apr-util-$APR_UTIL_VERSION*

#pcre
RUN cd /opt/ \
#	&& wget http://heanet.dl.sourceforge.net/project/pcre/pcre/$PCRE_VERSION/pcre-$PCRE_VERSION.tar.gz \
	&& tar -xzvf pcre-$PCRE_VERSION.tar.gz \
	&& cd pcre-$PCRE_VERSION \
	&& ./configure --prefix=/usr/local/pcre \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf pcre-$PCRE_VERSION*

#apache
RUN cd /opt/ \
#	&& wget http://apache.osuosl.org//httpd/httpd-$APACHE_VERSION.tar.gz \
	&& tar -xzvf httpd-$APACHE_VERSION.tar.gz \
	&& cd httpd-$APACHE_VERSION \
	&& ./configure \
		--prefix=/usr/local/apache \
		--with-apr=/usr/local/apr \
		--with-apr-util=/usr/local/apr-util/ \
		--with-pcre=/usr/local/pcre \
		--enable-so \
		--enable-proxy \
		--enable-cgi \
		--enable-mime-magic \
		--enable-expires \
		--enable-info \
		--enable-rewrite \
	&& make \
	&& make install \
	&& sed -i "s/#ServerName www.example.com:80/ServerName localhost/g" /usr/local/apache/conf/httpd.conf \
	&& sed -i 's/#LoadModule rewrite_module/LoadModule rewrite_module/g' /usr/local/apache/conf/httpd.conf \
	&& sed -i "s/#Include conf\/extra\/httpd-vhosts.conf/Include conf\/extra\/httpd-vhosts.conf/g" /usr/local/apache/conf/httpd.conf \
	&& cd ../ \
	&& rm -rf httpd-$APACHE_VERSION*

COPY apache/httpd-vhosts.conf /usr/local/apache/conf/extra/httpd-vhosts.conf
### -------------------------------------- apache end --------------------------------------

### -------------------------------------- php start --------------------------------------
ENV PHP_VERSION 5.3.29
ENV XDEBUG_VERSION 2.2.7

COPY php5.3/software/php-$PHP_VERSION.tar.gz /opt/php-$PHP_VERSION.tar.gz
COPY php5.3/software/xdebug-$XDEBUG_VERSION.tgz /opt/xdebug-$XDEBUG_VERSION.tgz

# php5.3
RUN cd /opt/ \
	&& tar -xzvf php-$PHP_VERSION.tar.gz \
	&& cd php-$PHP_VERSION \
	# 解决 「error: Cannot find libmysqlclient_r under /usr」
	&& ln -s /usr/lib64/mysql/libmysqlclient.so /usr/lib/ \
	# 解决 「error: Cannot find libmysqlclient_r under /usr」
	&& ln -s /usr/lib64/mysql/libmysqlclient_r.so /usr/lib/ \
	&& ./configure --prefix=/usr/local/php \
#		--with-config-file-path=	\
		--with-config-file-scan-dir=/usr/local/php/conf	\
		--with-apxs2=/usr/local/apache/bin/apxs \
		--with-mysql --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
		--enable-mbstring --enable-mbregex --enable-zip \
	&& make \
	&& make install \
	&& cp /opt/php-$PHP_VERSION/php.ini-development /usr/local/php/lib/php.ini \
	&& sed -i "s/;date.timezone =/date.timezone = \"Asia\/Shanghai\"/g" /usr/local/php/lib/php.ini \
	&& sed -i 's/short_open_tag = Off/short_open_tag = On/g' /usr/local/php/lib/php.ini \
	&& cd ../ \
	&& rm -rf php-$PHP_VERSION*

# apache 中 php 配置
COPY php5.3/php.conf /usr/local/apache/conf/php.conf
RUN echo "Include /usr/local/apache/conf/php.conf" >> /usr/local/apache/conf/httpd.conf

# xdebug
RUN cd /opt/ \
	&& tar -xzvf xdebug-$XDEBUG_VERSION.tgz \
	&& cd xdebug-$XDEBUG_VERSION \
	&& /usr/local/php/bin/phpize \
	&& ./configure --with-php-config=/usr/local/php/bin/php-config \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf xdebug-$XDEBUG_VERSION*

COPY php5.3/xdebug.ini /usr/local/php/conf/xdebug.ini
### -------------------------------------- php end --------------------------------------

### -------------------------------------- memcache start --------------------------------------
ENV MEMCACHED 1.4.33
ENV MEMCACHE 2.2.7

COPY memcached/software/memcached-$MEMCACHED.tar.gz /opt/memcached-$MEMCACHED.tar.gz
COPY php5.3/software/memcache-$MEMCACHE.tgz /opt/memcache-$MEMCACHE.tgz

RUN yum install libevent libevent-devel -y

# memcached 服务端
RUN cd /opt \
	&& tar -xzvf memcached-$MEMCACHED.tar.gz \
	&& cd memcached-$MEMCACHED \
	&& ./configure --prefix=/usr/local/memcached \
	&& make \
	&& make install \
	&& cd ../ \
	&& rm -rf memcached-$MEMCACHED*

# php memcache 扩展
RUN cd /opt \
	&& tar -xzvf memcache-$MEMCACHE.tgz \
	&& cd memcache-$MEMCACHE \
	&& /usr/local/php/bin/phpize \
	&& ./configure --with-php-config=/usr/local/php/bin/php-config \
	&& make && make install \
	&& cd ../ \
	&& rm -rf memcache-$MEMCACHE* \
	&& echo "[memcache]" >> /usr/local/php/lib/php.ini \
	&& echo "extension=/usr/local/php/lib/php/extensions/no-debug-zts-20090626/memcache.so" >> /usr/local/php/lib/php.ini
### -------------------------------------- memcache end --------------------------------------

### -------------------------------------- mysql start --------------------------------------
ENV MYSQL_VERSION 5.6.34

COPY mysql/software/mysql-$MYSQL_VERSION.tar.gz /opt/mysql-$MYSQL_VERSION.tar.gz
COPY mysql/init_mysql.sh /opt/init_mysql.sh
COPY mysql/my.cnf /etc/my.cnf

RUN yum install cmake bison ncurses -y

#mysql
RUN cd /opt \
	&& tar -xzvf mysql-$MYSQL_VERSION.tar.gz \
	&& cd mysql-$MYSQL_VERSION \
	&& cmake . \
	&& make \
	&& make install \
	&& cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysql \
	&& cd ../ \
	&& rm -rf mysql-$MYSQL_VERSION* \
	&& groupadd mysql \
	&& useradd -g mysql mysql \
	&& chmod u+x /opt/init_mysql.sh \
	&& /opt/init_mysql.sh
### -------------------------------------- mysql end --------------------------------------

EXPOSE 22 80 9000 3306